services:

  app:
    build: .
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
      nats: 
        condition: service_started
  
  db:
    image: postgres:16.3-alpine
    ports:
      - 5433:5432
    env_file: ./.env
    volumes:
      - pg_store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5

  nats:
    image: nats-streaming:latest
    ports:
      - 4222:4222
    env_file: ./.env

volumes:
  pg_store:
